## **Importing Libraries**

In [49]:
import pandas as pd #useful for loading dataset
import numpy as np #to perform array operations

## **Choose Dataset file from Local Directory**


In [50]:
from google.colab import files
uploaded = files.upload()

Saving DigitalAd_dataset.csv to DigitalAd_dataset (2).csv


## **Load Dataset**

In [51]:
dataset = pd.read_csv('DigitalAd_dataset.csv')
print(dataset)

     Age  Salary  Status
0     18   82000       0
1     29   80000       0
2     47   25000       1
3     45   26000       1
4     46   28000       1
..   ...     ...     ...
395   35   65000       0
396   26   80000       0
397   26   52000       0
398   20   86000       0
399   32   18000       0

[400 rows x 3 columns]


## **Summarize Dataset**

In [52]:
print(dataset.shape)
print(dataset.head(5))
print(dataset.tail(5))

(400, 3)
   Age  Salary  Status
0   18   82000       0
1   29   80000       0
2   47   25000       1
3   45   26000       1
4   46   28000       1
     Age  Salary  Status
395   35   65000       0
396   26   80000       0
397   26   52000       0
398   20   86000       0
399   32   18000       0


## **Segregate Dataset into Input(X) and Output(Y)**

In [53]:
x = dataset.iloc[:, :-1].values
print(x)

[[    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  18000]
 [    32 117000]
 [    27  20000]
 [    25  87000]
 [    23  66000]
 [    32 120000]
 [    59  83000]
 [    24  58000]
 [    24  19000]
 [    23  82000]
 [    22  63000]
 [    31  68000]
 [    25  80000]
 [    24  27000]
 [    20  2300

In [54]:
y = dataset.iloc[:, -1].values
print(y)

[0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1 1 1 0 0 1 1 0 1 1 0 1 1 0 1
 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 1 1
 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0 1 1 0 1 1 1 1 1 0 0 0 1 1 0
 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0 0 1 0 1 0 0 1 1 0 0 1 1 0 1
 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 0 0 1 1 0 1 1 1
 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0]


## **Splitting Dataset into Train & Test**

In [55]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test = train_test_split(x, y, test_size=0.5, random_state=0)

## **Feature Scaling**

In [56]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
print(x_train)



[[-6.02670885e-01  1.76218404e-01]
 [ 5.46958096e-01 -9.12275909e-01]
 [ 9.89123089e-01  4.70406056e-01]
 [ 2.81659100e-01  2.64474699e-01]
 [ 1.51972108e+00 -9.12275909e-01]
 [ 1.34285508e+00  3.52730995e-01]
 [-7.20728938e-02  2.23553197e+00]
 [-6.02670885e-01  5.58662352e-01]
 [ 7.23824093e-01  7.64593708e-01]
 [-9.56402880e-01  4.11568525e-01]
 [ 1.04793103e-01 -8.24019614e-01]
 [-1.04483588e+00  5.85433428e-02]
 [ 1.34285508e+00  5.85433428e-02]
 [-1.39856787e+00 -1.53006998e+00]
 [ 1.25442208e+00  5.88081117e-01]
 [-6.91103884e-01  5.58662352e-01]
 [-9.56402880e-01  5.58662352e-01]
 [ 1.04793103e-01 -2.65063075e-01]
 [-1.04483588e+00 -1.58890751e+00]
 [-9.56402880e-01 -3.82738136e-01]
 [ 1.07755609e+00 -1.47123245e+00]
 [ 1.43128808e+00 -2.94187652e-04]
 [-9.56402880e-01 -3.53319370e-01]
 [-1.48700087e+00 -1.58890751e+00]
 [ 6.35391095e-01  2.64474699e-01]
 [-7.79536883e-01 -1.23588233e+00]
 [-2.48938891e-01  5.85433428e-02]
 [-1.13326888e+00 -1.08878850e+00]
 [-6.02670885e-01  1

## **Algorithm Choosing & Training**

In [57]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression() #loading the algorithm
model.fit(x_train, y_train) #training the model

LogisticRegression()

## **Predicting Test Data**

In [58]:
y_pred = model.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]

In [59]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)

print("Accuracy of the Model: {0}%".format(accuracy_score(y_test,y_pred)*100))

[[117   5]
 [ 43  35]]
Accuracy of the Model: 76.0%


## **Manual testing of the Model**

In [60]:
age = int(input("Enter the Customer's Age: "))
salary = int(input("Enter the Customer's Salary: "))
x = [[age, salary]]
result = sc.transform(x)
result = model.predict(result)
if result == 1:
  print("Customer Will Buy")
else:
  print("Customer Won't Buy")


Enter the Customer's Age: 11
Enter the Customer's Salary: 1111111111
Customer Will Buy
